# GitHub Pages Configuration
title: "Tia Astor - Professional Resume"
description: "Systems Designer & Social Innovation Architect"
author: "Tia Astor"
email: "tiatheone@protonmail.com"

# GitHub Pages settings
github:
  repository_name: "TiaAstor"
  repository_nwo: "tiation/TiaAstor"
  repository_url: "https://github.com/tiation/TiaAstor"
  owner_name: "tiation"
  owner_url: "https://github.com/tiation"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files
exclude:
  - README.md
  - SETUP_INSTRUCTIONS.md
  - DEPLOYMENT_SUMMARY.md
  - setup_github.sh
  - .gitignore
